[package]
name = "rusty_trombone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="trombone"
path="src/lib/lib.rs"

[[bin]]
name="rusty_trombone"
path="src/bin/main.rs"

[dependencies]
hound = "*"
num="*"
rustfft="6.1.0"
